version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo no commands executed before building commands...
  build:
    commands:
      - export NODE_OPTIONS=--openssl-legacy-provider
      - rm -rf node_modules
      - npm install
      - echo npm install completed on `date`
      - npm run build
      - echo npm run build completed on `date`
  post_build:
    commands:
      - echo build completed on `date`
      - ls -l ./dist/shop/
artifacts:
  files:
    - dist/shop/*
    - dist/shop/assets/*
    - appspec.yml